// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiztastic.Data;

namespace Quiztastic.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181205202526_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Quiztastic.Models.Quiz.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnswerText");

                    b.Property<bool>("IsCorrect");

                    b.Property<string>("QuestionId");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Quiztastic.Models.Quiz.Question", b =>
                {
                    b.Property<string>("QuestionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("QuestionContent");

                    b.Property<string>("QuizId");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Quiztastic.Models.Quiz.Quiz", b =>
                {
                    b.Property<string>("QuizId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BadgeBookId");

                    b.Property<int>("NumberOfQuestions");

                    b.Property<string>("QuizDescription");

                    b.Property<string>("QuizName");

                    b.HasKey("QuizId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Quiztastic.Models.Quiz.Rank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BadgeBookId");

                    b.Property<string>("QuizId");

                    b.Property<int>("QuizScore");

                    b.HasKey("RankId");

                    b.HasIndex("QuizId");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("Quiztastic.Models.Quiz.Answer", b =>
                {
                    b.HasOne("Quiztastic.Models.Quiz.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("Quiztastic.Models.Quiz.Question", b =>
                {
                    b.HasOne("Quiztastic.Models.Quiz.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId");
                });

            modelBuilder.Entity("Quiztastic.Models.Quiz.Rank", b =>
                {
                    b.HasOne("Quiztastic.Models.Quiz.Quiz", "Quiz")
                        .WithMany("Ranks")
                        .HasForeignKey("QuizId");
                });
#pragma warning restore 612, 618
        }
    }
}
